### ISSUE TITLE
Implement Welcome Modal and Information Button in top-bar

### ISSUE THREAD

**Issue by emilijadunoska** [DLR-SC/ESID#372]
### Summary
The purpose of the initial welcome modal will be to show a welcome message when user first views the page, brief overview, as Introduction to the tool and its benefits in the series of slides. At the last slide they will be presented with an option to either start a certain tour or skip it and later access it at the information button.  The user can access the information button in the top bar whenever they need help OR they want to resume/load the tour again. 

## Checklists 
- [x] add a welcome modal component with slides 
- [x] make the modal appear only on if the user is a first time user 
- [x] add information button on top bar 
- [x] add tooltip after closing the modal that points out to the info button  
- [x] add a popover that appears on a click of the information button  
- [x] write unit tests 
- [x] add microchips for each onboarding tour on the last slide 
- [x] add translations in english & german  
- [x] fix styling
