### ISSUE TITLE
Implement the interactive onboarding tour

### ISSUE THREAD

**Issue by emilijadunoska** [DLR-SC/ESID#373]
### Summary
The purpose is to develop a guided and interactive tour, that highlights the key features: district map, scenario cards, chart, filter and etc. It is interactive, requiring users to click on elements to proceed. There’s an option to skip the tour. Also there is progress indicator. The tour should be accessed from the initial welcome modal or as an alternative in the information button in the forms of chips for each feature. 

## Checklists 
- [x] create a joyride tour steps component that will trigger a specific tour when clicked on a microchip 
- [x] allow tours to be completed multiple times.
- [x] Fix the bug that prevents completing one tour after another.
- [x] close the modal/popover before starting a tour.
- [x] make the tour interactive, requiring users to click on elements to proceed
- [x] update the popover text in the info button to display different text if all tours are completed
- [x] add content & translations
- [x] write tests
